name: SSL Expiry Checker

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check_ssl_expiry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ref: main

      - name: Set up Python and Node.js
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify Node.js version 16

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cryptography pyOpenSSL

      - name: Run SSL Expiry Checker
        id: run_script
        run: |
          DOMAINS="${{ secrets.DOMAINS }}"
          SSL_ALERTS=$(python .github/scripts/check_ssl_expiry.py "$DOMAINS")
          echo "SSL_ALERTS=$SSL_ALERTS" >> $GITHUB_ENV

      - name: Save SSL Alerts to Environment File
        run: echo "$SSL_ALERTS" >> ssl_alerts.env

      - name: Notify in Slack
        if: success()
        uses: rtCamp/action-slack-notify@v2
        with:
          entryPoint: "rtCamp/action-slack-notify@v2"
          args: |
            --status "Success"
            --args "$(cat ssl_alerts.env)"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
