name: SSL Expiry Check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Run script file
        run: |
           chmod +x .scripts/test.sh
           .scripts/test.sh
        shell: bash
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DOMAINS_SECRET: ${{ secrets.DOMAINS }}


    
    
      
      
